---
version: '3'
services: 
  icon_service:
    image: drivereu/icon-service:develop-latest
    environment:
      URL: http://${TESTBED_HOST}/icon-service/
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${TESTBED_HOST};PathPrefix:/icon-service/"

networks:
  traefik-net:
    external: true
  testbed-net:
    driver: overlay
  
