---
version: '3'
services:
  postgres:
    image: postgres:9.6
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TRIAL_ADMIN
    volumes:
       - postgres-data:/var/lib/postgresql/${DB_NAME}/data
    restart: unless-stopped

  afteractionreview:
    image: drivereu/after-action-review:latest
    depends_on:
      - postgres
    ports:
      - "${AARTOOL_PORT}:8095"
    environment:
      TESTBED_CONNECTION: 'false'
  
  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - postgres
    ports:
        - "${PGADMIN_PORT}:5050"
    restart: unless-stopped
  
volumes:
  postgres-data:
