---
version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports:
     - "3500:3500"
    volumes:
     - ./zookeeper/config/zookeeper.properties:/etc/kafka/zookeeper.properties
     - ./zookeeper/config/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
    environment:
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf'
      ZOOKEEPER_CLIENT_PORT: 3500
      ZOOKEEPER_TICK_TIME: 2000
  
  authorization_service:
    image: authzforce/server
    hostname: authz
    ports:
     - "8080:8080"
    volumes:
     - ./authzforce-ce-server/webapp-context.xml:/usr/local/tomcat/conf/Catalina/localhost/authzforce-ce.xml
     - ./authzforce-ce-server/data:/opt/authzforce-ce-server/data
    environment:
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Djavax.xml.accessExternalSchema=http -Xms2048m -Xmx2048m -XX:+UseConcMarkSweepGC -server"

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    links: 
     - authorization_service:authz
    depends_on:
      - zookeeper
      - authorization_service  
    ports:
      - "3501:3501"
      #- "9092:9092"
    volumes:
      - ./authzforce-ce-kafka-extensions:/opt/authzforce-ce-kafka-extensions
      - ./kafka/config/server_jaas.conf:/etc/kafka/server_jaas.conf
    environment:
      CLASSPATH: '/opt/authzforce-ce-kafka-extensions/lib/*' 
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/server_jaas.conf'     
      #KAFKA_LOG4J_LOGGERS: "kafka=INFO,org.apache.cxf=WARN,org.ow2.authzforce=INFO"
      # Comment line below and uncomment line above for production. Line below is for testing/debugging (e.g. all XACML requests/responses to/from authorization service's PDP are logged).
      KAFKA_LOG4J_LOGGERS: "kafka=INFO,org.apache.cxf=INFO,org.ow2.authzforce=DEBUG"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:3500'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:3501,PLAINTEXT://broker:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:3501,PLAINTEXT://0.0.0.0:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 100000000
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'PLAINTEXT'
      # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.ow2.authzforce.kafka.pep.CombinedXacmlAclAuthorizer'
      KAFKA_SUPER_USERS: 'User:admin'
      KAFKA_ORG_OW2_AUTHZFORCE_KAFKA_PEP_XACML_PDP_URL: 'http://authz:8080/authzforce-ce/domains/A0bdIbmGEeWhFwcKrC9gSQ/pdp' 
      KAFKA_ORG_OW2_AUTHZFORCE_KAFKA_PEP_XACML_REQ_TMPL_LOCATION: 'file:///opt/authzforce-ce-kafka-extensions/request.xacml.json.ftl'

  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "3502:3502"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:3502'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:3500'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'

  kafka_rest:
    image: confluentinc/cp-kafka-rest
    hostname: kafka_rest
    depends_on:
      - zookeeper
      - schema_registry
      - broker
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: kafka_rest
      KAFKA_REST_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:3500'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:3502'
      KAFKA_CONSUMER_REQUEST_TIMEOUT_MS: 30000
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'

  kafka_topics_ui:
    image: landoop/kafka-topics-ui
    hostname: kafka_topics_ui
    depends_on:
      - kafka_rest
    ports:
      - "3600:8000"
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka_rest:8082'
      PROXY: 'true'

  kafka_schema_registry_ui:
    image: landoop/schema-registry-ui
    hostname: kafka_schema_registry_ui
    depends_on:
      - schema_registry
    ports:
      - "3601:8000"
    environment:
      SCHEMAREGISTRY_URL: 'http://schema_registry:3502'
      PROXY: 'true'